//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModels.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlUniqueFault", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service.Faults")]
    [System.SerializableAttribute()]
    public partial class SqlUniqueFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/Add", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ViewModels.CustomerService.SqlUniqueFault), Action="http://tempuri.org/ICRUDServiceOf_Customer/AddSqlUniqueFaultFault", Name="SqlUniqueFault", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service.Faults")]
        int Add(Models.Customer entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/Add", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(Models.Customer entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/Update", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/UpdateResponse")]
        void Update(Models.Customer entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/Update", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Models.Customer entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/Delete", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/DeleteResponse")]
        void Delete(Models.Customer entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/Delete", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Models.Customer entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/SelectAll", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/SelectAllResponse")]
        Models.Customer[] SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/SelectAll", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/SelectAllResponse")]
        System.Threading.Tasks.Task<Models.Customer[]> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/SelectById", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/SelectByIdResponse")]
        Models.Customer SelectById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDServiceOf_Customer/SelectById", ReplyAction="http://tempuri.org/ICRUDServiceOf_Customer/SelectByIdResponse")]
        System.Threading.Tasks.Task<Models.Customer> SelectByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/SelectAllUnattendedCustomers", ReplyAction="http://tempuri.org/ICustomerService/SelectAllUnattendedCustomersResponse")]
        Models.Customer[] SelectAllUnattendedCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/SelectAllUnattendedCustomers", ReplyAction="http://tempuri.org/ICustomerService/SelectAllUnattendedCustomersResponse")]
        System.Threading.Tasks.Task<Models.Customer[]> SelectAllUnattendedCustomersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : ViewModels.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ViewModels.CustomerService.ICustomerService>, ViewModels.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(Models.Customer entity) {
            return base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(Models.Customer entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public void Update(Models.Customer entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Models.Customer entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(Models.Customer entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Models.Customer entity) {
            return base.Channel.DeleteAsync(entity);
        }
        
        public Models.Customer[] SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<Models.Customer[]> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public Models.Customer SelectById(int id) {
            return base.Channel.SelectById(id);
        }
        
        public System.Threading.Tasks.Task<Models.Customer> SelectByIdAsync(int id) {
            return base.Channel.SelectByIdAsync(id);
        }
        
        public Models.Customer[] SelectAllUnattendedCustomers() {
            return base.Channel.SelectAllUnattendedCustomers();
        }
        
        public System.Threading.Tasks.Task<Models.Customer[]> SelectAllUnattendedCustomersAsync() {
            return base.Channel.SelectAllUnattendedCustomersAsync();
        }
    }
}
